### ISSUE TITLE
DEX Liquidity Challenge

### ISSUE THREAD

**Issue by OceanRaymond** [oceanprotocol/s2-data-challenges#1]
- [x] create challenge: [#2](https://github.com/oceanprotocol/s2-data-challenges/issues/2)
- [x] publish challenge: [#3](https://github.com/oceanprotocol/s2-data-challenges/issues/3)
- [x] create tracking links
- [x] create visuals
- [x] create comms
- [x] communicate start
- [x] support
- [x] evaluate
- [x] communicate results
